embeddings {
  tensor_name: "ticker:08660"
  metadata_path: "08660/ticker/metadata.tsv"
  tensor_path: "08660/ticker/tensors.tsv"
}
embeddings {
  tensor_name: "day_of_the_week:08660"
  metadata_path: "08660/day_of_the_week/metadata.tsv"
  tensor_path: "08660/day_of_the_week/tensors.tsv"
}
embeddings {
  tensor_name: "month:08660"
  metadata_path: "08660/month/metadata.tsv"
  tensor_path: "08660/month/tensors.tsv"
}
embeddings {
  tensor_name: "earnings_date:08660"
  metadata_path: "08660/earnings_date/metadata.tsv"
  tensor_path: "08660/earnings_date/tensors.tsv"
}
embeddings {
  tensor_name: "cpi_report:08660"
  metadata_path: "08660/cpi_report/metadata.tsv"
  tensor_path: "08660/cpi_report/tensors.tsv"
}
